blank_issues_enabled: false
contact_links:
  - name: 📚❓ Ask a Documentation question
    url: https://github.com/syslog-ng/syslog-ng.github.io/discussions
    about: Ask questions and discuss the documentation related topics with other community members
  - name: Create a syslog-ng application issue
    url: https://github.com/syslog-ng/syslog-ng/issues
    about: Use this template for reporting an issue in the syslog-ng application.
  - name: Create a syslog-ng application feature request
    url: https://github.com/syslog-ng/syslog-ng/issues
    about: Use this template for creating a feature request in the syslog-ng application.
  - name: ❓ Ask a syslog-ng application question
    url: https://github.com/syslog-ng/syslog-ng/discussions
    about: Ask questions and discuss the syslog-ng application related topics with other community members
